# Generated by Django 5.0.10 on 2025-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='sr_no',
            field=models.CharField(max_length=255, verbose_name='Serial Number'),
        ),
    ]
